# Workflow ka naam
name: Java CI with Gradle

# Workflow kab chalega
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Jobs
jobs:
  build:
    # Machine ka type
    runs-on: ubuntu-latest

    # Steps
    steps:
      # Step 1: Code download karna
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Java (JDK) set up karna
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle' # Yahan 'gradle' likhna zaroori hai

      # Step 3: Gradle Wrapper ko execute permissions dena
      # Linux environment mein yeh zaroori hai
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 4: Gradle se project build aur test karna
      - name: Build with Gradle
        run: ./gradlew build

      # Docker Step 1: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .

      # Docker Step 3: Push image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
